FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build


FROM nginx:alpine

RUN rm /etc/nginx/conf.d/nginx.conf

# ✅ Copy nginx.conf SPA
COPY nginx.conf /etc/nginx/conf.d/nginx.conf

# ✅ Copy React build
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
